### ISSUE TITLE
Support of complex types for filters (array, object)

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/js-sdk#209]
Right now filters can have conditions that tests for a specific value that can be either `string`, `boolean` or `number`. The API supports the equal predicate for `object` and `array` too so we could support this directly and have filters like:
```yml
- type: filter
  conditions:
    foo: [1, 2, 3]
```
or
```yml
- type: filter
  conditions:
    foo: { bar: 42 }
``` 

It is now possible with a workaround to use advanced conditions with references 
eg:
```yml
- type: filter
  conditions:
    - key: foo[0]
       predicate: EQ
       value: 1
    - key: foo[1]
       predicate: EQ
       value: 2
    - key: foo[2]
       predicate: EQ
       value: 3
```
or
```yml
- type: filter
  conditions:
    - key: foo.bar
      predicate: EQ
      value: 42
```

This feature would make the definition easier to write
