### ISSUE TITLE
Support any ancestor for references in filter conditions

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/js-sdk#210]
Filter conditions in the processes can reference the previous step but for now, we can only access the result of the parent step.
We should be able to filter any previous step, the same way we do for the mapping of inputs.

The definition would be the following:
```yml
- type: filter
  conditions:
    - key: attr1
      stepKey: stepX
      predicate: EQ
      value: xxx
```

where `stepX` is the key of a previous step in the process.
